[workspace]
authors = ["Kasper Munch <kaspermunch@birc.au.dk>"]
channels = ["conda-forge"]
name = "svgd"
platforms = ["osx-arm64", "linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
jax = ">=0.6.0,<0.7"
numpy = ">=2.3.1,<3"
pandas = ">=2.3.0,<3"
seaborn = ">=0.13.2,<0.14"
jupyterlab = ">=4.4.4,<5"
nodejs = ">=22.13.0,<22.14"
tensorflow-probability = ">=0.25.0,<0.26"
tqdm = ">=4.67.1,<5"
jupyter = ">=1.1.1,<2"
ipywidgets = ">=8.1.7,<9"
equinox = ">=0.13.0,<0.14"
jaxlib = ">=0.6.0,<0.7"
pip = ">=25.1.1,<26"
ipykernel = ">=6.29.5,<7"
ffmpeg = ">=7.1.1,<8"
cereal = ">=1.3.2,<2"
zlib = ">=1.3.1,<2"
hdf5 = ">=1.14.6,<2"
